### ISSUE TITLE
Deprecated class workspace used

### ISSUE THREAD

**Issue by nicolasmartinelli** [fxdgear/atom-python-debugger#8]
Hello,

The deprecated class "workspace" is used in keymaps/python-debugger.cson, leading to a warning. Changing '.workspace' into '.atom-workspace' in keymaps/python-debugger.cson fixes the issue.

Regards.

**Comment by fxdgear** [comment]
Thanks, new version pushed.

**Comment by nicolasmartinelli** [comment]
My bad, I should have written to change '.workspace' into 'atom-workspace' (without the dot at the beginning).

**Comment by fxdgear** [comment]
@nicolasmartinelli ok thanks, updated again (sorry slow on the updates... super busy at work :(
