### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Sosoyan** [fxdgear/atom-python-debugger#9]
Requiring `View` from `atom` is no longer supported.
Please require `atom-space-pen-views` instead:
  `{View} = require 'atom-space-pen-views'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/exports/atom.js:66:11)
Object.<anonymous> (/Users/Sosoyan/.atom/packages/atom-python-debugger/lib/python-debugger-view.coffee:1:1)
Object.<anonymous> (/Users/Sosoyan/.atom/packages/atom-python-debugger/lib/python-debugger-view.coffee:10:4)
Module._compile (module.js:452:26)
```

**Comment by huguesfontenelle** [comment]
> Deprecated APIs will be removed when Atom 1.0 is released in June. Please update your packages.
http://blog.atom.io/2015/05/01/removing-deprecated-apis.html
